import { Fragment, useEffect, useState } from "react"
import { CalendarRange, Check, ChevronLeft, ChevronRight, Clock3, DollarSign, LoaderCircle, LockKeyhole, MapPin, RefreshCw, Search, Users } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { api, getApiMutationVersion, postJSON } from "@/lib/api"
import type { Bootstrap, Summary } from "@/lib/types"
import { compactNumber, displayDate, initials, localISO } from "@/lib/utils"

function PageIntro({ title, text, actions }: { title: string; text: string; actions?: React.ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="page-title">{title}</h1><p className="page-subtitle">{text}</p></div>{actions}</div> }
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Clock3; label: string; value: string; detail?: string }) { return <Card><CardContent className="flex items-center gap-4 !pt-5 sm:!pt-6"><div className="metric-icon"><Icon className="size-5" /></div><div className="min-w-0"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="metric-value mt-1">{value}</p>{detail && <p className="mt-1 text-[11px] text-muted-foreground">{detail}</p>}</div></CardContent></Card> }
function moveMonth(value:string,delta:number){const [year,month]=value.split("-").map(Number);const next=new Date(year,month-1+delta,1);return `${next.getFullYear()}-${String(next.getMonth()+1).padStart(2,"0")}`}

type OverviewCacheEntry = {
  data: Summary
  savedAt: number
  mutationVersion: number
}
const overviewCache = new Map<string, OverviewCacheEntry>()

export function OverviewView({ bootstrap }: { bootstrap: Bootstrap }) {
  const today = localISO()
  const [from, setFrom] = useState(`${today.slice(0,7)}-01`)
  const [to, setTo] = useState(today)
  const [worker, setWorker] = useState("")
  const [search, setSearch] = useState("")
  const [data, setData] = useState<Summary | null>(null)
  const [loading, setLoading] = useState(true)
  const load = async (force = false) => {
    const match = worker
      ? bootstrap.workers.find(w => w.name.toLowerCase() === worker.toLowerCase())
        || bootstrap.workers.find(w => w.name.toLowerCase().includes(worker.toLowerCase()))
      : null
    if (worker && !match) {
      toast.error(`No worker matches “${worker}”`)
      return
    }
    const p = new URLSearchParams({ from, to })
    if (match) p.set("worker_id", String(match.id))
    const key = p.toString()
    const cached = overviewCache.get(key)
    if (!force && cached && Date.now() - cached.savedAt < 5 * 60_000 && cached.mutationVersion === getApiMutationVersion()) {
      setData(cached.data)
      setLoading(false)
      return
    }
    setLoading(true)
    try {
      const result = await api<Summary>(`/api/summary?${p}`)
      overviewCache.set(key, { data: result, savedAt: Date.now(), mutationVersion: getApiMutationVersion() })
      setData(result)
    } catch(e) {
      toast.error(e instanceof Error ? e.message : "Unable to load records")
    } finally {
      setLoading(false)
    }
  }
  useEffect(() => { void load() }, [])
  const setPreset = (kind: "7"|"month"|"pay1"|"pay2") => { const now = new Date(); const y=now.getFullYear(), m=now.getMonth(); if(kind==="7") { const s=new Date(now); s.setDate(s.getDate()-6); setFrom(localISO(s)); setTo(today) } else if(kind==="month") { setFrom(`${today.slice(0,7)}-01`); setTo(today) } else { const last = new Date(y, m + 1, 0); setFrom(localISO(new Date(y,m,kind==="pay1"?1:16))); setTo(localISO(kind==="pay1" ? new Date(y,m,15) : last)) } }
  const visible = (data?.records || []).filter(record =>
    `${record.worker_name} ${record.work_date} ${record.status}`.toLowerCase().includes(search.toLowerCase())
  )
  return <div className="page"><PageIntro title="Workforce overview" text="A quick summary of the selected work period." />
    <Card className="mb-5"><CardContent className="grid gap-3 !pt-5 lg:grid-cols-[1fr_1fr_1.3fr_auto]"><label className="field-label">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label className="field-label">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><label className="field-label">Worker<Input list="workers" value={worker} onChange={e=>setWorker(e.target.value)} placeholder="All workers" /></label><Button className="self-end" disabled={loading} onClick={()=>void load(true)}>{loading?<LoaderCircle className="size-4 animate-spin"/>:<Search className="size-4"/>}{loading?"Loading…":"Apply"}</Button><div className="flex flex-wrap gap-2 lg:col-span-4">{[["7","Last 7 days"],["month","This month"],["pay1","1–15"],["pay2","16–end"]].map(([id,label])=><Button size="sm" variant="ghost" key={id} onClick={()=>setPreset(id as never)}>{label}</Button>)}</div></CardContent></Card>
    {loading && !data ? <div className="metric-grid mb-5">{[1,2,3,4].map(x=><Skeleton className="h-28" key={x}/>)}</div> : <>
      <div className="metric-grid mb-5"><Metric icon={Clock3} label="Total hours" value={compactNumber(data?.totals.hours)} /><Metric icon={Users} label="Active workers" value={compactNumber(data?.totals.active_workers,0)} /><Metric icon={CalendarRange} label="Worked days" value={compactNumber(data?.totals.worked_days,0)} /><Metric icon={Clock3} label="Overtime" value={`${compactNumber(data?.totals.overtime_hours)}h`} /></div>
      <Card className="mb-5"><CardHeader className="!flex-row items-center justify-between"><div><CardTitle>Period summary</CardTitle><CardDescription>{data ? `${displayDate(data.range.from,true)} – ${displayDate(data.range.to,true)}` : ""}</CardDescription></div><Button size="sm" variant="outline" disabled={loading} onClick={()=>void load(true)}><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Refresh</Button></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Regular hours",`${compactNumber(data?.totals.regular_hours)}h`],["Average workday",`${compactNumber(data?.totals.average_hours)}h`],["Off records",compactNumber(data?.totals.off_days,0)],["Extra pay",`$${compactNumber(data?.totals.extra_pay)}`],["Latest activity",data?.totals.last_worked_date?displayDate(data.totals.last_worked_date,true):"—"]].map(([label,value])=><div className="rounded-xl border bg-slate-50 p-4" key={label}><p className="text-xs font-semibold text-muted-foreground">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div>)}</div></CardContent></Card>
    </>}
    <Card><CardHeader className="!flex-col justify-between gap-3 sm:!flex-row sm:items-center"><div><CardTitle>Recent activity</CardTitle><CardDescription>Latest 50 of {compactNumber(data?.totals.record_count,0)} records · detailed location data stays on the Locations page</CardDescription></div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search recent activity…" /></div></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Worker</th><th>Status</th><th>Hours</th><th>Overtime</th><th>Extra pay</th></tr></thead><tbody>{visible.map(record=><tr key={String(record.id)}><td><strong>{displayDate(record.work_date,true)}</strong></td><td><div className="flex items-center gap-2"><span className="avatar">{initials(record.worker_name||"")}</span><strong>{record.worker_name}</strong></div></td><td><Badge variant={record.status==="worked"?"success":record.status==="off"?"secondary":"warning"}>{record.status}</Badge></td><td><strong className="text-primary">{compactNumber(record.total_hours)}h</strong></td><td>{compactNumber(record.overtime_hours)}h</td><td>{record.extra_pay?`$${compactNumber(record.extra_pay)}`:"—"}</td></tr>)}</tbody></table>{!visible.length&&<div className="p-12 text-center text-sm text-muted-foreground">No recent records match this search.</div>}</div></CardContent></Card>
  </div>
}

export function PayrollView() {
  const today=localISO(); const [month,setMonth]=useState(today.slice(0,7)); const [half,setHalf]=useState("1"); const [data,setData]=useState<any>(null); const [detail,setDetail]=useState<any>(null); const [search,setSearch]=useState(""); const [access,setAccess]=useState<any>(null); const [password,setPassword]=useState(""); const [unlocking,setUnlocking]=useState(false)
  const checkAccess=async()=>{try{setAccess(await api("/api/payroll/access"))}catch(e){toast.error(e instanceof Error?e.message:String(e))}}; useEffect(()=>{void checkAccess()},[])
  const load=async()=>{if(!access?.authorized)return;try{setData(await api(`/api/payroll?month=${month}&half=${half}`));setDetail(null)}catch(e){toast.error(String(e))}}; useEffect(()=>{void load()},[month,half,access?.authorized])
  const unlock=async(event:React.FormEvent)=>{event.preventDefault();if(!password)return;setUnlocking(true);try{await postJSON("/api/payroll/unlock",{password});setPassword("");await checkAccess();toast.success("Payroll Check unlocked for 8 hours.")}catch(e){toast.error(e instanceof Error?e.message:String(e))}finally{setUnlocking(false)}}
  const show=async(id:number)=>{try{setDetail(await api(`/api/payroll_worker_detail?worker_id=${id}&month=${month}&half=${half}`))}catch(e){toast.error(String(e))}}
  const check=async(w:any, checked:boolean)=>{try{await postJSON("/api/payroll_check",{worker_id:w.worker_id,period_start:data.period.from,checked});setData((d:any)=>({...d,totals:{...d.totals,checked:d.workers.filter((x:any)=>x.worker_id===w.worker_id?checked:x.checked).length},workers:d.workers.map((x:any)=>x.worker_id===w.worker_id?{...x,checked}:x)}))}catch(e){toast.error(String(e))}}
  if(!access)return <div className="page"><Card><CardContent className="flex items-center justify-center gap-3 py-20 text-sm text-muted-foreground"><LoaderCircle className="size-5 animate-spin"/>Checking Payroll Check access…</CardContent></Card></div>
  if(!access.authorized)return <div className="page"><div className="mx-auto max-w-lg py-10"><Card><CardHeader><span className="mb-2 grid size-12 place-items-center rounded-xl bg-blue-50 text-primary"><LockKeyhole className="size-6"/></span><CardTitle>Payroll Check is protected</CardTitle><CardDescription>Payroll totals, rates, and working history are available only to authorized Lark administrators or users with the Payroll Check password.</CardDescription></CardHeader><CardContent>{access.password_configured?<form className="grid gap-3" onSubmit={unlock}><label className="field-label">Payroll Check password<Input autoFocus type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><Button type="submit" disabled={!password||unlocking}>{unlocking?<LoaderCircle className="size-4 animate-spin"/>:<LockKeyhole className="size-4"/>}{unlocking?"Unlocking…":"Unlock Payroll Check"}</Button></form>:<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Password access is not configured. Add <code>PAYROLL_PASSWORD</code> in Vercel and redeploy, or add this user's Lark open ID to <code>LARK_ADMIN_OPEN_IDS</code>.</div>}</CardContent></Card></div></div>
  const workers=(data?.workers||[]).filter((w:any)=>w.worker_name.toLowerCase().includes(search.toLowerCase()))
  return <div className="page"><PageIntro title="Payroll check" text="Review hours first, then mark each worker as checked."/><Card className="mb-5"><CardContent className="flex flex-wrap items-end gap-3 !pt-5"><div className="flex items-end gap-2"><Button variant="outline" size="icon" onClick={()=>setMonth(value=>moveMonth(value,-1))}><ChevronLeft className="size-4"/></Button><label className="field-label">Month<Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><Button variant="outline" size="icon" onClick={()=>setMonth(value=>moveMonth(value,1))}><ChevronRight className="size-4"/></Button></div><div className="flex rounded-xl bg-muted p-1"><Button size="sm" variant={half==="1"?"default":"ghost"} onClick={()=>setHalf("1")}>1–15</Button><Button size="sm" variant={half==="2"?"default":"ghost"} onClick={()=>setHalf("2")}>16–end</Button></div><div className="ml-auto w-64"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search worker…"/></div></CardContent></Card>
  <div className="metric-grid mb-5"><Metric icon={Clock3} label="Hours" value={compactNumber(data?.totals.hours)}/><Metric icon={Users} label="Workers" value={compactNumber(data?.totals.workers,0)}/><Metric icon={DollarSign} label="Estimated cost" value={`$${compactNumber(data?.totals.estimated_salary)}`}/><Metric icon={Check} label="Checked" value={`${data?.totals.checked||0} / ${data?.workers?.length||0}`}/></div>
  <Card><CardHeader><CardTitle>{data?`${displayDate(data.period.from,true)} – ${displayDate(data.period.to,true)}`:"Payroll period"}</CardTitle><CardDescription>Click a worker to expand the working history directly below that worker.</CardDescription></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead><tr><th>Checked</th><th>Worker</th><th>Hours</th><th>CA overtime</th><th>Estimated cost</th><th>Days</th><th></th></tr></thead><tbody>{workers.map((w:any)=><Fragment key={w.worker_id}><tr onClick={()=>show(w.worker_id)} className="cursor-pointer"><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={!!w.checked} onChange={e=>void check(w,e.target.checked)} className="size-4 accent-[#2563eb]"/></td><td><div className="flex items-center gap-2"><span className="avatar">{initials(w.worker_name)}</span><strong className={w.worker_type === "W2" ? "text-red-600" : "text-slate-900"}>{w.worker_name}</strong><span className="badge">{w.worker_type}</span></div></td><td><strong className="text-lg text-primary">{compactNumber(w.hours)} <small className="text-xs">hrs</small></strong></td><td><div>{compactNumber(w.overtime_hours)}h × 1.5</div>{w.doubletime_hours>0&&<small className="text-orange-700">{compactNumber(w.doubletime_hours)}h × 2</small>}</td><td>${compactNumber(w.estimated_salary)}</td><td>{w.worked_days} <small className="text-muted-foreground">· {w.off_days} off</small></td><td><ChevronRight className={`size-4 text-muted-foreground transition-transform ${detail?.worker.id===w.worker_id?"rotate-90":""}`}/></td></tr>{detail?.worker.id===w.worker_id&&<tr className="bg-slate-50/70"><td colSpan={7} className="!p-4 sm:!p-6"><PayrollWorkerDetail detail={detail}/></td></tr>}</Fragment>)}</tbody></table></div></CardContent></Card></div>
}
function PayrollWorkerDetail({detail}:{detail:any}){return <div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">{detail.worker.name} · payment-period details</h3><p className="text-sm text-muted-foreground">{compactNumber(detail.totals.hours)} actual hours · {compactNumber(detail.totals.weighted_hours)} weighted hours · estimated ${compactNumber(detail.totals.estimated_salary)}</p></div><Badge variant={detail.worker.worker_type==="W2"?"warning":"secondary"}>{detail.worker.worker_type}</Badge></div><WorkingHistory days={detail.days||[]}/><div className="mt-5 grid gap-5 xl:grid-cols-2"><DetailTable title="Hours by location" rows={detail.locations}/><DetailTable title="Hours by cost center" rows={detail.cost_centers}/></div></div>}
function WorkingHistory({days}:{days:any[]}){return <div><div className="mb-3 flex items-end justify-between"><div><h3 className="text-base font-bold">Working history</h3><p className="text-xs text-muted-foreground">California weighting: regular ×1, overtime ×1.5, double time ×2</p></div><Badge variant="secondary">{days.length} days</Badge></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Location and time</th><th>Cost center</th><th>Regular</th><th>OT ×1.5</th><th>DT ×2</th><th>Actual</th><th>Weighted</th><th>Extra pay</th></tr></thead><tbody>{days.map((d:any)=><tr key={d.work_day_id}><td><strong>{displayDate(d.date,true)}</strong></td><td>{d.locations?.length?d.locations.map((l:any)=><div key={l.location_id}><strong>{l.name}</strong>{l.start_time&&l.end_time&&<small className="ml-1 text-muted-foreground">{l.start_time}–{l.end_time}</small>}<small className="ml-1 text-muted-foreground">{compactNumber(l.hours)}h</small></div>):"—"}</td><td>{d.cost_centers?.length?d.cost_centers.map((c:any)=><div key={c.id}>{c.name}<small className="ml-1 text-muted-foreground">{c.id}</small></div>):"—"}</td><td>{compactNumber(d.regular_hours)}h</td><td>{d.overtime_hours?<Badge variant="warning">{compactNumber(d.overtime_hours)}h</Badge>:"0h"}</td><td>{d.doubletime_hours?<Badge variant="warning">{compactNumber(d.doubletime_hours)}h</Badge>:"0h"}</td><td><strong>{compactNumber(d.total_hours)}h</strong></td><td><strong className="text-primary">{compactNumber(d.weighted_hours)}h</strong></td><td>{d.extra_pay?`$${compactNumber(d.extra_pay)}`:"—"}</td></tr>)}</tbody></table>{!days.length&&<div className="p-8 text-center text-sm text-muted-foreground">No worked days in this payment period.</div>}</div></div>}
function DetailTable({title,rows}:{title:string;rows:any[]}){return <div><h3 className="mb-2 text-sm font-bold">{title}</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Hours</th><th>Days</th></tr></thead><tbody>{rows.map((r:any)=><tr key={`${r.id||""}${r.name}`}><td><strong>{r.name}</strong>{r.id&&<small className="block text-muted-foreground">{r.id}</small>}</td><td>{compactNumber(r.hours)}</td><td>{r.days}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-xs text-muted-foreground">No details recorded.</div>}</div></div>}

export function LocationsView({ bootstrap }: { bootstrap: Bootstrap }) {
 const today=localISO(); const [location,setLocation]=useState(""); const [from,setFrom]=useState(`${today.slice(0,4)}-01-01`); const [to,setTo]=useState(today); const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false)
 const load=async()=>{const found=bootstrap.locations.find(x=>x.toLowerCase()===location.toLowerCase())||bootstrap.locations.find(x=>x.toLowerCase().includes(location.toLowerCase())); if(!found)return toast.error("Choose a location from the suggestions.");setLoading(true);try{setData(await api(`/api/location_detail?${new URLSearchParams({location:found,from,to})}`))}catch(e){toast.error(String(e))}finally{setLoading(false)}}
 return <div className="page"><PageIntro title="Location check" text="See job-site hours, workers, cost centers, and estimated labor cost."/><Card className="mb-5"><CardContent className="grid gap-3 !pt-5 md:grid-cols-[1.5fr_1fr_1fr_auto]"><label className="field-label">Location<Input list="locations" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Search address or site"/></label><label className="field-label">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field-label">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button className="self-end" disabled={loading} onClick={load}>{loading?<LoaderCircle className="size-4 animate-spin"/>:<Search className="size-4"/>}{loading?"Calculating…":"Check location"}</Button></CardContent></Card>{data&&<><div className="metric-grid mb-5"><Metric icon={Users} label="Workers" value={compactNumber(data.totals.workers,0)}/><Metric icon={Clock3} label="Hours" value={compactNumber(data.totals.hours)}/><Metric icon={DollarSign} label="Estimated cost" value={`$${compactNumber(data.totals.estimated_cost)}`} detail="Based on worker rates and weighted overtime"/><Metric icon={CalendarRange} label="Work days" value={compactNumber(data.totals.days,0)}/><Metric icon={MapPin} label="Date span" value={data.totals.first_date?`${displayDate(data.totals.first_date)}–${displayDate(data.totals.last_date)}`:"—"}/></div><Card><CardHeader><CardTitle>{data.location}</CardTitle><CardDescription>{displayDate(data.range.from,true)} – {displayDate(data.range.to,true)} · W-2 estimates include California overtime weighting; 1099 estimates use straight time. Extra pay is excluded because it is not assigned to a location.</CardDescription></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead><tr><th>Worker</th><th>Type</th><th>Hours</th><th>Estimated cost</th><th>Days</th><th>First day</th><th>Last day</th></tr></thead><tbody>{data.workers.map((w:any)=><tr key={w.worker_id}><td><div className="flex items-center gap-2"><span className="avatar">{initials(w.worker_name)}</span><strong>{w.worker_name}</strong></div></td><td><Badge variant={w.worker_type==="W2"?"warning":"secondary"}>{w.worker_type}</Badge></td><td><strong className="text-primary">{compactNumber(w.hours)}</strong></td><td className="font-semibold tabular-nums">${compactNumber(w.estimated_cost)}</td><td>{w.days}</td><td>{displayDate(w.first_date,true)}</td><td>{displayDate(w.last_date,true)}</td></tr>)}</tbody></table></div></CardContent></Card>{data.cost_centers?.length>0&&<Card className="mt-5"><CardHeader><CardTitle>Cost centers at this location</CardTitle><CardDescription>Hours are allocated from the selected location entries.</CardDescription></CardHeader><CardContent><DetailTable title="" rows={data.cost_centers}/></CardContent></Card>}</>}</div>
}
