import { Fragment, useEffect, useMemo, useState } from "react"
import { createColumnHelper, flexRender, getCoreRowModel, getFilteredRowModel, getSortedRowModel, useReactTable, type SortingState } from "@tanstack/react-table"
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { ArrowUpDown, CalendarRange, Check, ChevronRight, Clock3, DollarSign, Download, MapPin, Search, Users } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { api, postJSON } from "@/lib/api"
import type { Bootstrap, Summary } from "@/lib/types"
import { compactNumber, displayDate, initials, localISO } from "@/lib/utils"

function PageIntro({ title, text, actions }: { title: string; text: string; actions?: React.ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="page-title">{title}</h1><p className="page-subtitle">{text}</p></div>{actions}</div> }
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Clock3; label: string; value: string; detail?: string }) { return <Card><CardContent className="flex items-center gap-4 !pt-5 sm:!pt-6"><div className="metric-icon"><Icon className="size-5" /></div><div className="min-w-0"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="metric-value mt-1">{value}</p>{detail && <p className="mt-1 text-[11px] text-muted-foreground">{detail}</p>}</div></CardContent></Card> }

type RecordRow = Summary["records"][number]
const col = createColumnHelper<RecordRow>()

export function OverviewView({ bootstrap }: { bootstrap: Bootstrap }) {
  const today = localISO(); const [from, setFrom] = useState(`${today.slice(0,7)}-01`); const [to, setTo] = useState(today); const [worker, setWorker] = useState(""); const [search, setSearch] = useState(""); const [data, setData] = useState<Summary | null>(null); const [loading, setLoading] = useState(true); const [sorting, setSorting] = useState<SortingState>([{ id: "work_date", desc: true }])
  const load = async () => { setLoading(true); try { const match = worker ? bootstrap.workers.find(w => w.name.toLowerCase() === worker.toLowerCase()) || bootstrap.workers.find(w => w.name.toLowerCase().includes(worker.toLowerCase())) : null; if (worker && !match) throw new Error(`No worker matches “${worker}”`); const p = new URLSearchParams({ from, to }); if (match) p.set("worker_id", String(match.id)); setData(await api(`/api/summary?${p}`)) } catch(e) { toast.error(e instanceof Error ? e.message : "Unable to load records") } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const columns = useMemo(() => [
    col.accessor("work_date", { header: "Date", cell: x => displayDate(x.getValue(), true) }),
    col.accessor("worker_name", { header: "Worker", cell: x => <div className="flex items-center gap-2"><span className="avatar">{initials(x.getValue())}</span><strong>{x.getValue()}</strong></div> }),
    col.accessor("status", { header: "Status", cell: x => <Badge variant={x.getValue() === "worked" ? "success" : x.getValue() === "off" ? "secondary" : "warning"}>{x.getValue()}</Badge> }),
    col.accessor("locations", { header: "Location", cell: x => { const value=x.getValue(); return <span className="block max-w-[280px] truncate">{!value ? "—" : typeof value === "string" ? value : value.map(y => y.name).join(" • ") || "—"}</span> } }),
    col.accessor("start_time", { header: "Time", cell: x => x.row.original.status === "worked" ? `${x.getValue() || "08:30"}–${x.row.original.end_time || "16:30"}` : "—" }),
    col.accessor("cost_centers", { header: "Cost center", cell: x => x.getValue()?.map(c => `${c.name} · ${c.id}`).join(" / ") || "—" }),
    col.accessor("total_hours", { header: "Hours", cell: x => <strong className="text-base text-primary">{compactNumber(x.getValue())}</strong> }),
  ], [])
  const table = useReactTable({ data: data?.records || [], columns, state: { sorting, globalFilter: search }, onSortingChange: setSorting, onGlobalFilterChange: setSearch, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getFilteredRowModel: getFilteredRowModel() })
  const setPreset = (kind: "7"|"month"|"pay1"|"pay2") => { const now = new Date(); const y=now.getFullYear(), m=now.getMonth(); if(kind==="7") { const s=new Date(now); s.setDate(s.getDate()-6); setFrom(localISO(s)); setTo(today) } else if(kind==="month") { setFrom(`${today.slice(0,7)}-01`); setTo(today) } else { const last = new Date(y, m + 1, 0); setFrom(localISO(new Date(y,m,kind==="pay1"?1:16))); setTo(localISO(kind==="pay1" ? new Date(y,m,15) : last)) } }
  return <div className="page"><PageIntro title="Workforce overview" text="Hours, attendance, and field records in one clear view." actions={<Button variant="outline" onClick={() => location.assign(`/api/export?from=${from}&to=${to}`)}><Download className="size-4" /> Export Excel</Button>} />
    <Card className="mb-5"><CardContent className="grid gap-3 !pt-5 lg:grid-cols-[1fr_1fr_1.3fr_auto]"><label className="field-label">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)} /></label><label className="field-label">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)} /></label><label className="field-label">Worker<Input list="workers" value={worker} onChange={e=>setWorker(e.target.value)} placeholder="All workers" /></label><Button className="self-end" onClick={load}><Search className="size-4" /> Apply</Button><div className="flex flex-wrap gap-2 lg:col-span-4">{[["7","Last 7 days"],["month","This month"],["pay1","1–15"],["pay2","16–end"]].map(([id,label])=><Button size="sm" variant="ghost" key={id} onClick={()=>setPreset(id as never)}>{label}</Button>)}</div></CardContent></Card>
    {loading ? <div className="metric-grid mb-5">{[1,2,3,4].map(x=><Skeleton className="h-28" key={x}/>)}</div> : <><div className="metric-grid mb-5"><Metric icon={Clock3} label="Total hours" value={compactNumber(data?.totals.hours)} /><Metric icon={Users} label="Active workers" value={compactNumber(data?.totals.active_workers,0)} /><Metric icon={CalendarRange} label="Worked days" value={compactNumber(data?.totals.worked_days,0)} /><Metric icon={DollarSign} label="Extra pay" value={`$${compactNumber(data?.totals.extra_pay)}`} /></div>
    <div className="mb-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Card><CardHeader><CardTitle>Daily workload</CardTitle><CardDescription>Recorded hours across the selected period</CardDescription></CardHeader><CardContent className="h-[260px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data?.daily || []}><CartesianGrid vertical={false} stroke="#E2E8F0"/><XAxis dataKey="date" tickFormatter={x=>displayDate(x)} tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={x=>displayDate(String(x),true)} formatter={x=>[`${compactNumber(x)} hrs`,"Hours"]}/><Area type="monotone" dataKey="hours" stroke="#2563EB" strokeWidth={2.5} fill="#DBEAFE" fillOpacity={0.8}/></AreaChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>Period snapshot</CardTitle><CardDescription>{data ? `${displayDate(data.range.from,true)} – ${displayDate(data.range.to,true)}` : ""}</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-sky-50 p-4"><p className="text-xs text-muted-foreground">Worked</p><strong className="mt-1 block text-2xl">{data?.totals.worked_days}</strong></div><div className="rounded-xl bg-slate-100 p-4"><p className="text-xs text-muted-foreground">Off</p><strong className="mt-1 block text-2xl">{data?.totals.off_days}</strong></div></div><div className="mt-4 rounded-xl border p-4"><p className="text-xs text-muted-foreground">Average hours / worked day</p><strong className="mt-1 block text-2xl text-primary">{compactNumber(data?.totals.worked_days ? data.totals.hours/data.totals.worked_days : 0)}</strong></div></CardContent></Card></div></>}
    <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Work records</CardTitle><CardDescription>{table.getFilteredRowModel().rows.length} entries</CardDescription></div><div className="relative w-full max-w-xs"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records…" /></div></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead>{table.getHeaderGroups().map(hg=><tr key={hg.id}>{hg.headers.map(h=><th key={h.id}><button className="flex items-center gap-1" onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown className="size-3"/></button></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id}>{row.getVisibleCells().map(cell=><td key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{!table.getRowModel().rows.length&&<div className="p-12 text-center text-sm text-muted-foreground">No records match this view.</div>}</div></CardContent></Card>
  </div>
}

export function PayrollView() {
  const today=localISO(); const [month,setMonth]=useState(today.slice(0,7)); const [half,setHalf]=useState("1"); const [data,setData]=useState<any>(null); const [detail,setDetail]=useState<any>(null); const [search,setSearch]=useState("")
  const load=async()=>{try{setData(await api(`/api/payroll?month=${month}&half=${half}`));setDetail(null)}catch(e){toast.error(String(e))}}; useEffect(()=>{void load()},[month,half])
  const show=async(id:number)=>{try{setDetail(await api(`/api/payroll/worker_detail?worker_id=${id}&month=${month}&half=${half}`))}catch(e){toast.error(String(e))}}
  const check=async(w:any, checked:boolean)=>{try{await postJSON("/api/payroll/check",{worker_id:w.worker_id,period_start:data.period.from,checked});setData((d:any)=>({...d,totals:{...d.totals,checked:d.workers.filter((x:any)=>x.worker_id===w.worker_id?checked:x.checked).length},workers:d.workers.map((x:any)=>x.worker_id===w.worker_id?{...x,checked}:x)}))}catch(e){toast.error(String(e))}}
  const workers=(data?.workers||[]).filter((w:any)=>w.worker_name.toLowerCase().includes(search.toLowerCase()))
  return <div className="page"><PageIntro title="Payroll check" text="Review hours first, then mark each worker as checked."/><Card className="mb-5"><CardContent className="flex flex-wrap items-end gap-3 !pt-5"><label className="field-label">Month<Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="flex rounded-xl bg-muted p-1"><Button size="sm" variant={half==="1"?"default":"ghost"} onClick={()=>setHalf("1")}>1–15</Button><Button size="sm" variant={half==="2"?"default":"ghost"} onClick={()=>setHalf("2")}>16–end</Button></div><div className="ml-auto w-64"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search worker…"/></div></CardContent></Card>
  <div className="metric-grid mb-5"><Metric icon={Clock3} label="Hours" value={compactNumber(data?.totals.hours)}/><Metric icon={Users} label="Workers" value={compactNumber(data?.totals.workers,0)}/><Metric icon={DollarSign} label="Estimated cost" value={`$${compactNumber(data?.totals.estimated_salary)}`}/><Metric icon={Check} label="Checked" value={`${data?.totals.checked||0} / ${data?.workers?.length||0}`}/></div>
  <Card><CardHeader><CardTitle>{data?`${displayDate(data.period.from,true)} – ${displayDate(data.period.to,true)}`:"Payroll period"}</CardTitle><CardDescription>Click a worker to expand the working history directly below that worker.</CardDescription></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead><tr><th>Checked</th><th>Worker</th><th>Hours</th><th>CA overtime</th><th>Estimated cost</th><th>Days</th><th></th></tr></thead><tbody>{workers.map((w:any)=><Fragment key={w.worker_id}><tr onClick={()=>show(w.worker_id)} className="cursor-pointer"><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={!!w.checked} onChange={e=>void check(w,e.target.checked)} className="size-4 accent-[#2563eb]"/></td><td><div className="flex items-center gap-2"><span className="avatar">{initials(w.worker_name)}</span><strong className={w.worker_type === "W2" ? "text-red-600" : "text-slate-900"}>{w.worker_name}</strong><span className="badge">{w.worker_type}</span></div></td><td><strong className="text-lg text-primary">{compactNumber(w.hours)} <small className="text-xs">hrs</small></strong></td><td><div>{compactNumber(w.overtime_hours)}h × 1.5</div>{w.doubletime_hours>0&&<small className="text-orange-700">{compactNumber(w.doubletime_hours)}h × 2</small>}</td><td>${compactNumber(w.estimated_salary)}</td><td>{w.worked_days} <small className="text-muted-foreground">· {w.off_days} off</small></td><td><ChevronRight className={`size-4 text-muted-foreground transition-transform ${detail?.worker.id===w.worker_id?"rotate-90":""}`}/></td></tr>{detail?.worker.id===w.worker_id&&<tr className="bg-slate-50/70"><td colSpan={7} className="!p-4 sm:!p-6"><PayrollWorkerDetail detail={detail}/></td></tr>}</Fragment>)}</tbody></table></div></CardContent></Card></div>
}
function PayrollWorkerDetail({detail}:{detail:any}){return <div><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">{detail.worker.name} · payment-period details</h3><p className="text-sm text-muted-foreground">{compactNumber(detail.totals.hours)} actual hours · {compactNumber(detail.totals.weighted_hours)} weighted hours · estimated ${compactNumber(detail.totals.estimated_salary)}</p></div><Badge variant={detail.worker.worker_type==="W2"?"warning":"secondary"}>{detail.worker.worker_type}</Badge></div><WorkingHistory days={detail.days||[]}/><div className="mt-5 grid gap-5 xl:grid-cols-2"><DetailTable title="Hours by location" rows={detail.locations}/><DetailTable title="Hours by cost center" rows={detail.cost_centers}/></div></div>}
function WorkingHistory({days}:{days:any[]}){return <div><div className="mb-3 flex items-end justify-between"><div><h3 className="text-base font-bold">Working history</h3><p className="text-xs text-muted-foreground">California weighting: regular ×1, overtime ×1.5, double time ×2</p></div><Badge variant="secondary">{days.length} days</Badge></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Time</th><th>Location</th><th>Cost center</th><th>Regular</th><th>OT ×1.5</th><th>DT ×2</th><th>Actual</th><th>Weighted</th><th>Extra pay</th></tr></thead><tbody>{days.map((d:any)=><tr key={d.work_day_id}><td><strong>{displayDate(d.date,true)}</strong></td><td>{d.start_time&&d.end_time?`${d.start_time}–${d.end_time}`:"—"}</td><td>{d.locations?.length?d.locations.map((l:any)=><div key={l.location_id}><strong>{l.name}</strong><small className="ml-1 text-muted-foreground">{compactNumber(l.hours)}h</small></div>):"—"}</td><td>{d.cost_centers?.length?d.cost_centers.map((c:any)=><div key={c.id}>{c.name}<small className="ml-1 text-muted-foreground">{c.id}</small></div>):"—"}</td><td>{compactNumber(d.regular_hours)}h</td><td>{d.overtime_hours?<Badge variant="warning">{compactNumber(d.overtime_hours)}h</Badge>:"0h"}</td><td>{d.doubletime_hours?<Badge variant="warning">{compactNumber(d.doubletime_hours)}h</Badge>:"0h"}</td><td><strong>{compactNumber(d.total_hours)}h</strong></td><td><strong className="text-primary">{compactNumber(d.weighted_hours)}h</strong></td><td>{d.extra_pay?`$${compactNumber(d.extra_pay)}`:"—"}</td></tr>)}</tbody></table>{!days.length&&<div className="p-8 text-center text-sm text-muted-foreground">No worked days in this payment period.</div>}</div></div>}
function DetailTable({title,rows}:{title:string;rows:any[]}){return <div><h3 className="mb-2 text-sm font-bold">{title}</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Hours</th><th>Days</th></tr></thead><tbody>{rows.map((r:any)=><tr key={`${r.id||""}${r.name}`}><td><strong>{r.name}</strong>{r.id&&<small className="block text-muted-foreground">{r.id}</small>}</td><td>{compactNumber(r.hours)}</td><td>{r.days}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-8 text-center text-xs text-muted-foreground">No details recorded.</div>}</div></div>}

export function LocationsView({ bootstrap }: { bootstrap: Bootstrap }) {
 const today=localISO(); const [location,setLocation]=useState(""); const [from,setFrom]=useState(`${today.slice(0,4)}-01-01`); const [to,setTo]=useState(today); const [data,setData]=useState<any>(null)
 const load=async()=>{const found=bootstrap.locations.find(x=>x.toLowerCase()===location.toLowerCase())||bootstrap.locations.find(x=>x.toLowerCase().includes(location.toLowerCase())); if(!found)return toast.error("Choose a location from the suggestions."); try{setData(await api(`/api/location_detail?${new URLSearchParams({location:found,from,to})}`))}catch(e){toast.error(String(e))}}
 return <div className="page"><PageIntro title="Location check" text="See who worked at a job site, for how long, and on which dates."/><Card className="mb-5"><CardContent className="grid gap-3 !pt-5 md:grid-cols-[1.5fr_1fr_1fr_auto]"><label className="field-label">Location<Input list="locations" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Search address or site"/></label><label className="field-label">From<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field-label">To<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button className="self-end" onClick={load}><Search className="size-4"/>Check location</Button></CardContent></Card>{data&&<><div className="metric-grid mb-5"><Metric icon={Users} label="Workers" value={compactNumber(data.totals.workers,0)}/><Metric icon={Clock3} label="Hours" value={compactNumber(data.totals.hours)}/><Metric icon={CalendarRange} label="Work days" value={compactNumber(data.totals.days,0)}/><Metric icon={MapPin} label="Date span" value={data.totals.first_date?`${displayDate(data.totals.first_date)}–${displayDate(data.totals.last_date)}`:"—"}/></div><Card><CardHeader><CardTitle>{data.location}</CardTitle><CardDescription>{displayDate(data.range.from,true)} – {displayDate(data.range.to,true)}</CardDescription></CardHeader><CardContent><div className="table-wrap"><table className="data-table"><thead><tr><th>Worker</th><th>Hours</th><th>Days</th><th>First day</th><th>Last day</th></tr></thead><tbody>{data.workers.map((w:any)=><tr key={w.worker_id}><td><div className="flex items-center gap-2"><span className="avatar">{initials(w.worker_name)}</span><strong>{w.worker_name}</strong></div></td><td><strong className="text-primary">{compactNumber(w.hours)}</strong></td><td>{w.days}</td><td>{displayDate(w.first_date,true)}</td><td>{displayDate(w.last_date,true)}</td></tr>)}</tbody></table></div></CardContent></Card></>}</div>
}
