import { useEffect, useState } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { AlertTriangle, BrainCircuit, Check, Download, FileSpreadsheet, LoaderCircle, Sparkles, Upload } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { EmptyState } from "@/components/ui/empty-state"
import { Input, Textarea } from "@/components/ui/input"
import { api, postJSON } from "@/lib/api"
import type { Bootstrap } from "@/lib/types"
import { displayDate, localISO } from "@/lib/utils"

const aiSchema=z.object({text:z.string().min(10,"Paste at least one complete work entry."),year:z.number().min(2020).max(2100),consent:z.boolean().refine(Boolean,"Confirm the Gemini notice.")})
type AiForm=z.infer<typeof aiSchema>
export function AiView({ bootstrap,onSaved }:{bootstrap:Bootstrap;onSaved:()=>void}){
 const [records,setRecords]=useState<any[]>([]);const [warnings,setWarnings]=useState<string[]>([]);const [loading,setLoading]=useState(false);const {register,handleSubmit,formState:{errors}}=useForm<AiForm>({resolver:zodResolver(aiSchema),defaultValues:{year:Number(localISO().slice(0,4)),consent:false,text:""}})
 const analyze=async(values:AiForm)=>{setLoading(true);try{const result:any=await postJSON("/api/ai/parse",values);setWarnings(result.warnings||[]);setRecords((result.records||[]).map((r:any)=>({...r,selected:!!r.ready&&r.confidence!=="low",saved:false,cost_center_text:r.cost_center_text||(r.cost_centers||[]).map((c:any)=>typeof c==="string"?c:`${c.name} (${c.id})`).join(" ; "),location_text:(r.locations||[]).map((x:any)=>typeof x==="string"?x:x.name).join(" ; ")})));toast.success(`Gemini found ${result.records?.length||0} records. Review before saving.`)}catch(e){toast.error(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 const update=(i:number,p:any)=>setRecords(x=>x.map((r,j)=>j===i?{...r,...p}:r));const save=async()=>{const selected=records.filter(r=>r.selected&&!r.saved);if(!selected.length)return;const missingCenter=selected.find(r=>r.status==="worked"&&!String(r.cost_center_text||"").trim());if(missingCenter)return toast.error(`Choose a cost center for ${missingCenter.worker_name || "each worked record"}.`);try{const result:any=await postJSON("/api/ai/apply",{records:selected.map(r=>({worker_name:r.worker_name,date:r.date,status:r.status,locations:String(r.location_text||"").split(";").map((x:string)=>x.trim()).filter(Boolean),regular_hours:r.regular_hours,overtime_hours:Number(r.overtime_hours||0),total_hours:Number(r.total_hours||8),extra_pay:Number(r.extra_pay||0),start_time:r.start_time||"",end_time:r.end_time||"",cost_centers:String(r.cost_center_text||"").split(";").map((x:string)=>x.trim()).filter(Boolean),notes:r.notes||""}))});setRecords(old=>old.map(r=>r.selected?{...r,saved:true,selected:false}:r));toast.success(`Confirmed and saved ${result.saved||selected.length} records.`);onSaved()}catch(e){toast.error(String(e))}}
 return <div className="page"><div className="mb-6"><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-700"><Sparkles className="size-3"/>Gemini assisted</div><h1 className="page-title">AI reading</h1><p className="page-subtitle">Turn text messages and job notes into structured records, then verify everything before it updates the database.</p></div>
 <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><CardTitle>Paste working information</CardTitle><CardDescription>Names, dates, locations, hours, overtime, and extra pay can appear in many formats.</CardDescription></CardHeader><CardContent><form onSubmit={handleSubmit(analyze)} className="grid gap-4"><Textarea {...register("text")} className="min-h-72 resize-y" placeholder={'07/01 Cristian and Eduardo\n16970 Cypress Way\n\n07/02 Cristian and Eduardo 1049 Woodland Ave'} />{errors.text&&<p className="text-xs text-red-600">{errors.text.message}</p>}<label className="field-label">Entry year<Input type="number" {...register("year",{valueAsNumber:true})}/></label><label className="flex items-start gap-3 rounded-xl border bg-amber-50 p-3 text-xs leading-5 text-amber-900"><input type="checkbox" {...register("consent")} className="mt-1 size-4"/><span>This text will be sent to Google Gemini for extraction. Do not paste information you are not authorized to share.</span></label>{errors.consent&&<p className="text-xs text-red-600">{errors.consent.message}</p>}<Button size="lg" disabled={!bootstrap.ai_configured||loading}>{loading?<LoaderCircle className="size-4 animate-spin"/>:<BrainCircuit className="size-4"/>}{loading?"Gemini is reading…":"Analyze with Gemini"}</Button>{!bootstrap.ai_configured&&<p className="text-center text-xs text-red-600">Gemini API key is not configured on the server.</p>}</form></CardContent></Card>
 <Card><CardHeader><CardTitle>What happens next</CardTitle><CardDescription>The AI never writes directly to your timesheet.</CardDescription></CardHeader><CardContent className="grid gap-4">{[["1","Gemini extracts possible records"],["2","You review names, dates, sites, and hours"],["3","Only selected records are confirmed and saved"]].map(([n,t])=><div className="flex items-center gap-3" key={n}><span className="grid size-8 place-items-center rounded-full bg-accent text-xs font-bold text-primary">{n}</span><span className="text-sm">{t}</span></div>)}</CardContent></Card></div>
 {(records.length>0||warnings.length>0)&&<Card className="mt-5"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Review extracted records</CardTitle><CardDescription>Correct any mistakes before confirming.</CardDescription></div><Button disabled={!records.some(r=>r.selected&&!r.saved)} onClick={save}><Check className="size-4"/>Confirm selected</Button></CardHeader><CardContent className="grid gap-3">{warnings.map((w,i)=><div key={i} className="rounded-lg bg-amber-50 p-3 text-xs text-amber-800"><AlertTriangle className="mr-2 inline size-4"/>{w}</div>)}{records.map((r,i)=><div key={i} className={`rounded-xl border p-4 ${r.saved?"bg-sky-50 opacity-75":r.issues?.length?"border-amber-300":""}`}><div className="mb-3 flex flex-wrap items-center gap-2"><input type="checkbox" checked={!!r.selected} disabled={r.saved} onChange={e=>update(i,{selected:e.target.checked})}/><Badge variant={r.confidence==="high"?"success":"warning"}>{r.confidence||"low"} confidence</Badge>{r.existing&&<Badge>Updates existing day</Badge>}<span className="ml-auto text-xs text-muted-foreground">{r.source_excerpt}</span></div><div className="grid gap-3 md:grid-cols-3"><label className="field-label">Date<Input type="date" value={r.date||""} onChange={e=>update(i,{date:e.target.value})}/></label><label className="field-label">Worker<Input list="workers" value={r.worker_name||""} onChange={e=>update(i,{worker_name:e.target.value})}/></label><label className="field-label">Status<select className="h-10 rounded-xl border bg-white px-3" value={r.status||"worked"} onChange={e=>update(i,{status:e.target.value})}><option value="worked">Worked</option><option value="off">Off</option></select></label><label className="field-label md:col-span-2">Locations · separate with ;<Input value={r.location_text||""} onChange={e=>update(i,{location_text:e.target.value})}/></label><label className="field-label">Hours<Input type="number" step=".25" value={r.total_hours??8} onChange={e=>update(i,{total_hours:e.target.value})}/></label><label className="field-label md:col-span-2">Cost centers · required, separate with ;<Input list="centers" required={r.status==="worked"} value={r.cost_center_text||""} onChange={e=>update(i,{cost_center_text:e.target.value})}/></label><label className="field-label">Overtime<Input type="number" step=".25" value={r.overtime_hours||0} onChange={e=>update(i,{overtime_hours:e.target.value})}/></label></div>{r.issues?.length>0&&<p className="mt-3 text-xs text-amber-700">{r.issues.join(" · ")}</p>}</div>)}</CardContent></Card>}</div>
}

export function TransferView({bootstrap}:{bootstrap:Bootstrap}){
 void bootstrap
 const [preview,setPreview]=useState<any>(null);const [loading,setLoading]=useState(false);const [importing,setImporting]=useState(false);const [result,setResult]=useState<any>(null)
 const loadPreview=async()=>{setLoading(true);try{const value:any=await api("/api/lark/migration");setPreview(value);setResult(null);toast.success("Cloud workbooks verified. No records were changed.")}catch(e){toast.error(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
 const importVerified=async()=>{if(!preview?.safe_to_write)return toast.error("Run a successful preview first.");if(!window.confirm(`Import ${preview.counts.work_days.toLocaleString()} work days and ${preview.counts.location_entries.toLocaleString()} location entries into Lark Base? Existing keyed records will not be overwritten.`))return;setImporting(true);setResult(null);const results:any={};try{const stages=["workers","cost_centers","work_days","location_entries","audit"];for(const [index,stage] of stages.entries()){toast.info(`Migration step ${index+1} of ${stages.length}: ${stage.replaceAll("_"," ")}`);const value:any=await postJSON("/api/lark/migration",{confirm:"IMPORT VERIFIED PREVIEW",stage});results[value.table]=value.result;toast.success(`${value.table} complete · ${value.result.created} created · ${value.result.already_present} already present`)}setResult({results});toast.success("Verified workforce data imported into Lark Base.")}catch(e){toast.error(`${e instanceof Error?e.message:String(e)} You can safely click Import again to resume.`)}finally{setImporting(false)}}
 const metrics=preview?[['Workers',preview.counts.workers],['Work days',preview.counts.work_days],['Locations',preview.counts.location_entries],['Cost centers',preview.counts.cost_centers]]:[]
 return <div className="page"><div className="mb-6"><h1 className="page-title">Cloud data migration</h1><p className="page-subtitle">Verify the three controlled Lark Drive workbooks, then import them safely into Lark Base.</p></div><Card><CardHeader><CardTitle>2026 standardized workforce data</CardTitle><CardDescription>Preview is read-only. Import creates only missing keyed records, so retrying will not overwrite records already in Base.</CardDescription></CardHeader><CardContent className="grid gap-5"><div className="flex flex-wrap gap-3"><Button onClick={loadPreview} disabled={loading||importing} variant="outline">{loading?<LoaderCircle className="size-4 animate-spin"/>:<FileSpreadsheet className="size-4"/>}{loading?"Checking Lark Drive…":"Preview cloud migration"}</Button><Button onClick={importVerified} disabled={!preview?.safe_to_write||loading||importing}>{importing?<LoaderCircle className="size-4 animate-spin"/>:<Upload className="size-4"/>}{importing?"Importing into Lark Base…":"Import verified preview"}</Button></div>{preview&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value])=><div className="rounded-xl border bg-slate-50 p-4" key={label}><p className="text-xs font-semibold text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl">{Number(value).toLocaleString()}</strong></div>)}</div><div className={`rounded-xl border p-4 ${preview.safe_to_write?"border-emerald-200 bg-emerald-50":"border-red-200 bg-red-50"}`}><div className="flex items-center gap-2"><Badge variant={preview.safe_to_write?"success":"destructive"}>{preview.safe_to_write?"Verified":"Blocked"}</Badge><strong>{displayDate(preview.date_range.start,true)} – {displayDate(preview.date_range.end,true)}</strong></div><p className="mt-2 text-sm">{preview.counts.warnings} entries will remain in Needs review. Historical cost centers remain blank until confirmed.</p></div></>}{result&&<div className="rounded-xl border border-sky-200 bg-sky-50 p-4"><div className="flex items-center gap-2"><Check className="size-5 text-emerald-700"/><strong>Migration complete</strong></div><p className="mt-2 text-sm">Created {Object.values(result.results||{}).reduce((sum:number,item:any)=>sum+Number(item.created||0),0).toLocaleString()} missing Base records. Existing records were preserved.</p></div>}</CardContent></Card></div>
}

export function ReviewView({onSaved,bootstrap}:{onSaved:()=>void;bootstrap:Bootstrap}){
 const [items,setItems]=useState<any[]>([]);const load=async()=>{try{const d:any=await api("/api/review");setItems(d.items)}catch(e){toast.error(String(e))}};useEffect(()=>{void load()},[]);const update=(id:number,p:any)=>setItems(x=>x.map(r=>r.id===id?{...r,...p}:r));const save=async(r:any)=>{if(r.status==="worked"&&!String(r.locations||"").trim())return toast.error("Enter the confirmed location.");if(r.status==="worked"&&!r.cost_center_id)return toast.error("Choose a cost center.");try{await postJSON(`/api/review/${r.id}`,{status:r.status,total_hours:r.status==="worked"?Number(r.total_hours??8):0,extra_pay:Number(r.extra_pay||0),locations:r.status==="worked"?[{name:String(r.locations).trim(),hours:null}]:[],cost_centers:r.status==="worked"?[{id:r.cost_center_id}]:[],notes:"Confirmed from review queue"});toast.success("Entry confirmed.");onSaved();void load()}catch(e){toast.error(String(e))}}
 return <div className="page"><div className="mb-6"><h1 className="page-title">Needs review</h1><p className="page-subtitle">Resolve uncertain workbook entries so reports remain trustworthy.</p></div>{!items.length?<Card><EmptyState icon={Check} title="Everything is confirmed" description="No uncertain source entries remain."/></Card>:<div className="grid gap-3">{items.map(r=><Card key={r.id}><CardContent className="grid gap-3 !pt-5 md:grid-cols-[1.2fr_130px_100px_1.4fr_1.4fr_auto]"><div><strong>{r.worker_name}</strong><small className="block text-muted-foreground">{displayDate(r.work_date,true)}</small><code className="mt-2 block text-xs text-amber-700">{r.original_text||"(blank)"}</code></div><label className="field-label">Status<select className="h-10 rounded-xl border px-3" value={r.status} onChange={e=>update(r.id,{status:e.target.value})}><option value="worked">Worked</option><option value="off">Off</option></select></label><label className="field-label">Hours<Input type="number" value={r.total_hours??8} onChange={e=>update(r.id,{total_hours:e.target.value})}/></label><label className="field-label">Location<Input value={r.locations||""} onChange={e=>update(r.id,{locations:e.target.value})}/></label><label className="field-label">Cost center<select className="h-10 rounded-xl border bg-white px-3" value={r.cost_center_id||""} onChange={e=>update(r.id,{cost_center_id:e.target.value})}><option value="">Select required cost center</option>{bootstrap.cost_centers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select></label><Button className="self-end" onClick={()=>save(r)}>Confirm</Button></CardContent></Card>)}</div>}</div>
}
