import { useEffect, useMemo, useState } from "react"
import { Check, ChevronDown, ChevronLeft, ChevronRight, Clipboard, Copy, Plus, Save, Search, Trash2, Users, X } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { LocationEditor, cleanLocations, rangeHours } from "@/components/location-editor"
import { api, postJSON } from "@/lib/api"
import type { Bootstrap, WorkLocation, WorkRecord, Worker } from "@/lib/types"
import { compactNumber, displayDate, initials, localISO } from "@/lib/utils"

type Editable = WorkRecord & { dirty: boolean; existing: boolean; expanded?: boolean }
const blankLocation = (): WorkLocation => ({ name: "", hours: 8, start_time: "08:30", end_time: "16:30", cost_centers: [] })
const normalize = (raw: any, date: string): Editable => ({ worker_id: raw.worker_id, worker_name: raw.worker_name, work_date: raw.work_date || date, status: raw.status || "worked", total_hours: raw.total_hours ?? 8, overtime_hours: raw.overtime_hours ?? Math.max(0, Number(raw.total_hours ?? 8)-8), extra_pay: raw.extra_pay || 0, start_time: "", end_time: "", notes: raw.notes || "", locations: raw.locations?.length ? raw.locations.map((l:any)=>({...l,start_time:l.start_time||"",end_time:l.end_time||"",hours:rangeHours(l.start_time||"",l.end_time||"")??l.hours??null,cost_centers:l.cost_centers||[]})) : [blankLocation()], cost_centers: raw.cost_centers || [], dirty: false, existing: !!raw.day_id || !!raw.id })
const clearedRecord = (record: Editable): Editable => ({...normalize({worker_id:record.worker_id,worker_name:record.worker_name,work_date:record.work_date,status:"worked",total_hours:8,overtime_hours:0,extra_pay:0,locations:[]},record.work_date),expanded:record.expanded})
function minutes(value:string){const [hour,minute]=value.split(":").map(Number);return hour*60+minute}
function timeFromMinutes(value:number){const rounded=Math.round(value);if(rounded<0||rounded>23*60+59)return "";return `${String(Math.floor(rounded/60)).padStart(2,"0")}:${String(rounded%60).padStart(2,"0")}`}
function fitLastLocationToTotal(locations:WorkLocation[],total:number){const rows=locations.map(row=>({...row}));if(!rows.length)return rows;const lastIndex=rows.length-1,last=rows[lastIndex];if(!last.start_time)return rows;let prior=0;for(const row of rows.slice(0,lastIndex)){const hours=rangeHours(row.start_time,row.end_time);if(hours===null)return rows;prior+=hours}const remaining=total-prior;if(remaining<=0)return rows;const end=timeFromMinutes(minutes(last.start_time)+remaining*60);if(!end)return rows;last.end_time=end;last.hours=rangeHours(last.start_time,end);return rows}
function timeResult(locations:WorkLocation[]){const rows=locations.filter(x=>x.name.trim()||x.start_time||x.end_time||x.hours!==null);const entered=rows.filter(x=>x.start_time||x.end_time);if(!entered.length)return {total:null as number|null,error:""};if(entered.length!==rows.length||entered.some(x=>!x.start_time||!x.end_time))return {total:null,error:"Time conflict: enter both Start and End for every location, or leave all location times blank."};const ranges=rows.map((x,index)=>({name:x.name.trim()||`Location ${index+1}`,start:minutes(x.start_time),end:minutes(x.end_time)}));const invalid=ranges.find(x=>x.end<=x.start);if(invalid)return {total:null,error:`Time conflict: ${invalid.name} must end after it starts.`};const sorted=[...ranges].sort((a,b)=>a.start-b.start);for(let i=1;i<sorted.length;i++)if(sorted[i].start<sorted[i-1].end)return {total:null,error:`Time conflict: ${sorted[i-1].name} overlaps ${sorted[i].name}.`};return {total:Math.round(ranges.reduce((sum,x)=>sum+(x.end-x.start)/60,0)*100)/100,error:""}}
function payload(r: Editable) { const locations=cleanLocations(r.locations); return { worker_id:r.worker_id,status:r.status,total_hours:r.status==="worked"?Number(r.total_hours??8):0,overtime_hours:r.status==="worked"?Number(r.overtime_hours||0):0,extra_pay:r.status==="worked"?Number(r.extra_pay||0):0,start_time:"",end_time:"",locations:r.status==="worked"?locations:[],cost_centers:r.status==="worked"?Array.from(new Map(locations.flatMap(l=>l.cost_centers).map(c=>[c.id,c])).values()):[],notes:r.notes||""} }
function validate(r:Editable){const locations=cleanLocations(r.locations);if(r.status==="worked"&&!locations.length)return "Add at least one location.";const missingCenter=locations.find(x=>!x.cost_centers.length);if(r.status==="worked"&&missingCenter)return `Choose a cost center for ${missingCenter.name}.`;if(r.status!=="worked")return "";const timing=timeResult(locations);if(timing.error)return timing.error;const total=Number(r.total_hours??8),overtime=Number(r.overtime_hours||0);if(timing.total!==null&&Math.abs(timing.total-total)>.01)return `Time conflict: location ranges total ${compactNumber(timing.total)}h, but Total hours is ${compactNumber(total)}h.`;const expected=Math.max(total-8,0);if(Math.abs(expected-overtime)>.01)return `Time conflict: ${compactNumber(total)} total hours requires ${compactNumber(expected)} overtime hours, not ${compactNumber(overtime)}h.`;return ""}
function cellText(r:Editable){if(r.status==="off")return "off";const loc=cleanLocations(r.locations).map(l=>`${l.name}${l.hours==null?"":`(${compactNumber(l.hours)})`}`).join(";");const ot=Number(r.overtime_hours||Math.max(0,Number(r.total_hours)-8));return `${loc}${ot?`, ot ${compactNumber(ot)}h`:""}${Number(r.extra_pay)?`, ex $${compactNumber(r.extra_pay)}`:""}`||"—"}

function RecordEditor({ record, update, bootstrap }: { record: Editable; update: (patch: Partial<Editable>)=>void; bootstrap: Bootstrap }) {
 const worked=record.status==="worked";const changeLocations=(locations:WorkLocation[])=>{const timing=timeResult(locations);update(timing.total===null||timing.error?{locations}:{locations,total_hours:timing.total,overtime_hours:Math.max(timing.total-8,0)})};const changeTotal=(total:number)=>update({locations:fitLastLocationToTotal(record.locations,total),total_hours:total,overtime_hours:Math.max(total-8,0)});const changeOvertime=(overtime:number)=>{const total=overtime>0?8+overtime:Math.min(Number(record.total_hours??8),8);update({locations:fitLastLocationToTotal(record.locations,total),total_hours:total,overtime_hours:overtime})};return <div className="mt-4 grid gap-4 border-t pt-4"><LocationEditor value={record.locations} onChange={changeLocations} suggestions={bootstrap.locations} costCenters={bootstrap.cost_centers} disabled={!worked}/><div className="entry-grid"><label className="field-label">Total hours<Input type="number" min="0" max="24" step=".25" disabled={!worked} value={record.total_hours} onChange={e=>changeTotal(Number(e.target.value))}/></label><label className="field-label">Overtime hours<Input type="number" min="0" max="16" step=".25" disabled={!worked} value={record.overtime_hours||0} onChange={e=>changeOvertime(Number(e.target.value))}/></label><label className="field-label">Extra pay<Input type="number" min="0" step="1" disabled={!worked} value={record.extra_pay} onChange={e=>update({extra_pay:Number(e.target.value)})}/></label></div><p className="text-xs text-muted-foreground">The first location defaults to 08:30–16:30. New locations continue from the previous End and fill the remaining time to 8 hours. Location times, Total Hours, and Overtime Hours stay synchronized; changing either hour total adjusts the last location's End. Conflicts are blocked when saved.</p><label className="field-label">Notes<Input disabled={!worked} value={record.notes} onChange={e=>update({notes:e.target.value})} placeholder="Optional"/></label><div className="flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs text-white"><span className="text-slate-400">Normalized cell</span><code className="overflow-hidden text-ellipsis">{cellText(record)}</code></div></div>
}

export function DailyEntryView({ bootstrap }: { bootstrap: Bootstrap }) {
 const [date,setDate]=useState(localISO());const [records,setRecords]=useState<Editable[]>([]);const [search,setSearch]=useState("");const [copied,setCopied]=useState<Editable|null>(null);const draftKey=`speed-daily-draft:${date}`
 const load=async()=>{try{const data=await api<any>(`/api/day?date=${date}`);let rows=data.workers.map((x:any)=>normalize(x,date));try{const drafts=JSON.parse(localStorage.getItem(draftKey)||"[]");rows=rows.map((r:Editable)=>{const d=drafts.find((x:any)=>x.worker_id===r.worker_id);return d?{...r,...d,dirty:true}:r})}catch{}setRecords(rows)}catch(e){toast.error(String(e))}};useEffect(()=>{void load()},[date])
 const setRow=(id:number,patch:Partial<Editable>)=>setRecords(old=>{const next=old.map(r=>r.worker_id===id?{...r,...patch,dirty:true}:r);try{localStorage.setItem(draftKey,JSON.stringify(next.filter(r=>r.dirty)))}catch{}return next})
 const save=async(rows:Editable[])=>{for(const r of rows){const error=validate(r);if(error){toast.error(`${r.worker_name}: ${error}`);return}}try{await postJSON("/api/day",{date,records:rows.map(payload)});setRecords(old=>{const next=old.map(r=>rows.some(x=>x.worker_id===r.worker_id)?{...r,dirty:false,existing:true}:r);const remaining=next.filter(r=>r.dirty);try{remaining.length?localStorage.setItem(draftKey,JSON.stringify(remaining)):localStorage.removeItem(draftKey)}catch{}return next});toast.success(`Saved ${rows.length} ${rows.length===1?"worker":"workers"}.`)}catch(e){toast.error(String(e))}}
 const clearRecord=async(r:Editable)=>{if(!window.confirm(`Clear ${r.worker_name}'s record for ${displayDate(date,true)}? This deletes the saved Lark record.`))return;try{if(r.existing)await postJSON("/api/day/clear",{worker_id:r.worker_id,date});setRecords(old=>{const next=old.map(item=>item.worker_id===r.worker_id?clearedRecord(item):item);const remaining=next.filter(item=>item.dirty);try{remaining.length?localStorage.setItem(draftKey,JSON.stringify(remaining)):localStorage.removeItem(draftKey)}catch{}return next});toast.success(`${r.worker_name}'s record was cleared.`)}catch(e){toast.error(String(e))}}
 const visible=records.filter(r=>r.worker_name?.toLowerCase().includes(search.toLowerCase()));const dirty=records.filter(r=>r.dirty)
 return <div className="page"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="page-title">Daily entry</h1><p className="page-subtitle">Choose one day, then update every worker who worked that day.</p></div><div className="flex w-full gap-2 sm:w-auto"><Button variant="outline" size="icon" className="shrink-0" onClick={()=>{const d=new Date(`${date}T12:00`);d.setDate(d.getDate()-1);setDate(localISO(d))}}><ChevronLeft className="size-4"/></Button><Input className="min-w-0 flex-1 sm:w-40" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Button variant="outline" size="icon" className="shrink-0" onClick={()=>{const d=new Date(`${date}T12:00`);d.setDate(d.getDate()+1);setDate(localISO(d))}}><ChevronRight className="size-4"/></Button></div></div>
 <div className="metric-grid mb-5"><Mini label="Worked" value={records.filter(r=>r.status==="worked").length}/><Mini label="Off" value={records.filter(r=>r.status==="off").length}/><Mini label="Hours" value={compactNumber(records.filter(r=>r.status==="worked").reduce((a,r)=>a+Number(r.total_hours),0))}/><Mini label="Unsaved" value={dirty.length}/></div>
 <Card><CardHeader className="!flex-col justify-between sm:!flex-row sm:items-center"><div><CardTitle>Workers for {displayDate(date,true)}</CardTitle><CardDescription>Drafts are kept in this browser until saved.</CardDescription></div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find worker…"/></div></CardHeader><CardContent className="grid gap-3">{visible.map(r=><Card className={r.dirty?"border-amber-300":"shadow-none"} key={r.worker_id}><div className="p-4"><div className="flex flex-wrap items-center gap-3"><span className="avatar">{initials(r.worker_name)}</span><strong className="mr-auto">{r.worker_name}</strong><div className="flex rounded-lg bg-muted p-1"><Button size="sm" variant={r.status==="worked"?"default":"ghost"} onClick={()=>setRow(r.worker_id,{status:"worked",total_hours:r.total_hours||8})}>Worked</Button><Button size="sm" variant={r.status==="off"?"default":"ghost"} onClick={()=>setRow(r.worker_id,{status:"off",total_hours:0})}>Off</Button></div><Button size="sm" variant="ghost" onClick={()=>{setCopied(structuredClone(r));toast.success(`Copied ${r.worker_name}`)}}><Copy className="size-4"/>Copy</Button><Button size="sm" variant="ghost" disabled={!copied} onClick={()=>copied&&setRow(r.worker_id,{...structuredClone(copied),worker_id:r.worker_id,worker_name:r.worker_name,dirty:true})}><Clipboard className="size-4"/>Paste</Button><Button size="sm" disabled={!r.dirty} onClick={()=>save([r])}><Save className="size-4"/>Save</Button><Button size="sm" variant="ghost" className="text-red-600 hover:text-red-700" onClick={()=>void clearRecord(r)}><Trash2 className="size-4"/>Clear record</Button><Button variant="ghost" size="icon" onClick={()=>setRow(r.worker_id,{expanded:!r.expanded})}><ChevronDown className={`size-4 transition ${r.expanded?"rotate-180":""}`}/></Button></div>{r.expanded&&<RecordEditor record={r} bootstrap={bootstrap} update={p=>setRow(r.worker_id,p)}/>}</div></Card>)}</CardContent></Card>
 {dirty.length>0&&<div className="fixed bottom-20 right-5 z-40 flex items-center gap-4 rounded-2xl border bg-white p-3 pl-5 shadow-xl md:bottom-6"><span className="text-sm"><strong>{dirty.length}</strong> unsaved · draft protected</span><Button onClick={()=>save(dirty)}><Save className="size-4"/>Save all</Button></div>}</div>
}
function Mini({label,value}:{label:string;value:string|number}){return <Card><CardContent className="!pt-5"><p className="text-xs font-semibold text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></CardContent></Card>}

export function WorkerEntryView({ bootstrap }: { bootstrap: Bootstrap }) {
 const today=localISO();const [workerName,setWorkerName]=useState("");const [month,setMonth]=useState(today.slice(0,7));const [data,setData]=useState<any>(null);const [selected,setSelected]=useState<Set<string>>(new Set());const [copyOpen,setCopyOpen]=useState(false);const [targets,setTargets]=useState<number[]>([]);const worker=useMemo(()=>bootstrap.workers.find(w=>w.name.toLowerCase()===workerName.toLowerCase())||bootstrap.workers.find(w=>w.name.toLowerCase().includes(workerName.toLowerCase())),[workerName,bootstrap])
 const load=async()=>{if(!worker)return toast.error("Choose a worker from the suggestions.");try{const x=await api<any>(`/api/worker-month?worker_id=${worker.id}&month=${month}`);setData({...x,days:x.days.map((d:any)=>normalize({...d,worker_id:worker.id,worker_name:worker.name},d.work_date))});setSelected(new Set())}catch(e){toast.error(String(e))}}
 const setDay=(date:string,patch:Partial<Editable>)=>setData((d:any)=>({...d,days:d.days.map((r:Editable)=>r.work_date===date?{...r,...patch,dirty:true}:r)}));const save=async(rows:Editable[])=>{for(const r of rows){const error=validate(r);if(error)return toast.error(`${displayDate(r.work_date)}: ${error}`)}try{await postJSON("/api/worker-days",{worker_id:data.worker.id,records:rows.map(r=>({date:r.work_date,...payload(r)}))});setData((d:any)=>({...d,days:d.days.map((r:Editable)=>rows.includes(r)?{...r,dirty:false,existing:true}:r)}));toast.success(`Saved ${rows.length} days.`)}catch(e){toast.error(String(e))}}
 const clearDay=async(r:Editable)=>{if(!window.confirm(`Clear ${data.worker.name}'s record for ${displayDate(r.work_date,true)}? This deletes the saved Lark record.`))return;try{if(r.existing)await postJSON("/api/day/clear",{worker_id:data.worker.id,date:r.work_date});setData((d:any)=>({...d,days:d.days.map((item:Editable)=>item.work_date===r.work_date?clearedRecord(item):item)}));setSelected((selected:Set<string>)=>{const next=new Set(selected);next.delete(r.work_date);return next});toast.success(`Record for ${displayDate(r.work_date,true)} was cleared.`)}catch(e){toast.error(String(e))}}
 const copy=async()=>{const rows=data.days.filter((d:Editable)=>selected.has(d.work_date));try{const result:any=await postJSON("/api/worker-days/copy",{source_worker_id:data.worker.id,target_worker_ids:targets,records:rows.map((r:Editable)=>({date:r.work_date,...payload(r)}))});toast.success(`Copied ${result.days} days to ${result.target_workers.length} workers.`);setCopyOpen(false);setTargets([])}catch(e){toast.error(String(e))}}
 return <div className="page"><div className="mb-6"><h1 className="page-title">Worker entry</h1><p className="page-subtitle">Choose one worker and record multiple days in a month.</p></div><Card className="mb-5"><CardContent className="flex flex-wrap items-end gap-3 !pt-5"><label className="field-label min-w-64 flex-1">Worker<Input list="workers" value={workerName} onChange={e=>setWorkerName(e.target.value)} placeholder="Search worker name"/></label><label className="field-label">Month<Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><Button onClick={load}><Search className="size-4"/>Load month</Button></CardContent></Card>
 {!data?<Card><CardContent className="py-16 text-center"><Users className="mx-auto mb-3 size-10 text-primary"/><h3 className="font-bold">Select a worker to begin</h3><p className="mt-1 text-sm text-muted-foreground">Their entire month will appear here for quick entry.</p></CardContent></Card>:<><div className="mb-4 flex flex-wrap items-center gap-2"><strong className="mr-auto">{data.worker.name} · {month}</strong><Badge>{selected.size} selected</Badge><Button variant="outline" disabled={!selected.size} onClick={()=>setCopyOpen(true)}><Copy className="size-4"/>Copy selected days</Button><Button disabled={!data.days.some((x:Editable)=>x.dirty)} onClick={()=>save(data.days.filter((x:Editable)=>x.dirty))}><Save className="size-4"/>Save edited</Button></div><div className="grid gap-3">{data.days.map((r:Editable)=>{const weekday=new Date(`${r.work_date}T12:00`).toLocaleDateString("en-US",{weekday:"short"});return <Card key={r.work_date} className={r.dirty?"border-amber-300":""}><div className="p-4"><div className="flex flex-wrap items-center gap-3"><input type="checkbox" className="size-4 accent-[#2563eb]" checked={selected.has(r.work_date)} onChange={e=>setSelected(s=>{const n=new Set(s);e.target.checked?n.add(r.work_date):n.delete(r.work_date);return n})}/><div className="w-24"><strong>{displayDate(r.work_date)}</strong><small className="ml-2 text-muted-foreground">{weekday}</small></div><div className="flex rounded-lg bg-muted p-1"><Button size="sm" variant={r.status==="worked"?"default":"ghost"} onClick={()=>setDay(r.work_date,{status:"worked",total_hours:r.total_hours||8})}>Worked</Button><Button size="sm" variant={r.status==="off"?"default":"ghost"} onClick={()=>setDay(r.work_date,{status:"off",total_hours:0})}>Off</Button></div><span className="min-w-0 flex-1 truncate text-xs text-muted-foreground">{cellText(r)}</span><strong className="text-primary">{compactNumber(r.total_hours)}h</strong><Button size="sm" disabled={!r.dirty} onClick={()=>save([r])}>Save</Button><Button size="sm" variant="ghost" className="text-red-600 hover:text-red-700" onClick={()=>void clearDay(r)}><Trash2 className="size-4"/>Clear record</Button><Button variant="ghost" size="icon" onClick={()=>setDay(r.work_date,{expanded:!r.expanded})}><ChevronDown className={`size-4 ${r.expanded?"rotate-180":""}`}/></Button></div>{r.expanded&&<RecordEditor record={r} bootstrap={bootstrap} update={p=>setDay(r.work_date,p)}/>}</div></Card>})}</div></>}
 <Dialog open={copyOpen} onOpenChange={setCopyOpen}><DialogContent><DialogHeader><DialogTitle>Copy {selected.size} days</DialogTitle><DialogDescription>Select every worker who shared this schedule. Existing records on those dates will be replaced.</DialogDescription></DialogHeader><div className="max-h-72 overflow-auto rounded-xl border p-2">{bootstrap.workers.filter(w=>w.id!==data?.worker.id).map((w:Worker)=><label key={w.id} className="flex cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-muted"><input type="checkbox" checked={targets.includes(w.id)} onChange={e=>setTargets(t=>e.target.checked?[...t,w.id]:t.filter(id=>id!==w.id))}/><span className="avatar">{initials(w.name)}</span><span>{w.name}</span></label>)}</div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={()=>setCopyOpen(false)}>Cancel</Button><Button disabled={!targets.length} onClick={copy}><Copy className="size-4"/>Copy to {targets.length} workers</Button></div></DialogContent></Dialog></div>
}
